name: Django CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}  
          SSH_USERNAME: ${{ secrets.GIT_USER }}
          SSH_PASS: ${{ secrets.GIT_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$DROPLET_IP << 'EOF'
          cd book &&
          ls &&
          pwd &&
          git pull https://$SSH_USERNAME:$SSH_PASS@github.com/$SSH_USERNAME/book.git &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          sudo systemctl restart supervisor &&
          exit
          EOF
